version: '3.8'

services:
  streamlit_app:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
