name: Sphinx Documentation

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme  # Add other dependencies here
          pip install sphinx-autobuild

      - name: Build documentation
        run: |
          cd docs  # Adjust this if your docs are in a different directory
          make html

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "notyusheng@gmail.com"
          git config --global user.name "notyusheng"
          git clone --branch=gh-pages https://${{ secrets.GITHUB_TOKEN }}@github.com/NotYuSheng/Multimodal-Large-Language-Model.git gh-pages
          cd gh-pages
          cp -r ../docs/_build/html/* .  # Copy the built docs to the gh-pages branch
          git add .
          git commit -m "Update Sphinx documentation"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/NotYuSheng/Multimodal-Large-Language-Model.git gh-pages
